# Generated by Django 3.2.15 on 2022-09-06 16:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='城市描述')),
                ('descrice', models.TextField(verbose_name='城市描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '城市信息',
                'verbose_name_plural': '城市信息',
            },
        ),
        migrations.CreateModel(
            name='CourseOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='机构名称')),
                ('descrice', models.TextField(verbose_name='机构描述')),
                ('address', models.CharField(max_length=100, verbose_name='机构地址')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击数量')),
                ('favourite_num', models.IntegerField(default=0, verbose_name='收藏数量')),
                ('images', models.ImageField(upload_to='courses/%Y/%m', verbose_name='机构封面')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '机构信息',
                'verbose_name_plural': '机构信息',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='教师名称')),
                ('work_years', models.IntegerField(default=0, verbose_name='工作年限')),
                ('work_company', models.IntegerField(default=0, verbose_name='公司名称')),
                ('work_position', models.IntegerField(default=0, verbose_name='工作职位')),
                ('specialty', models.CharField(max_length=50, verbose_name='教学特点')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击数量')),
                ('favourite_num', models.IntegerField(default=0, verbose_name='收藏数量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.courseorganization', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
            },
        ),
    ]
