# Generated by Django 3.2.15 on 2022-09-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citylist',
            old_name='descrice',
            new_name='describe',
        ),
        migrations.RenameField(
            model_name='courseorganization',
            old_name='descrice',
            new_name='describe',
        ),
    ]
