# Generated by Django 3.2.15 on 2022-09-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_courseorganization_cateogry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorganization',
            name='images',
            field=models.ImageField(upload_to='organization/%Y/%m', verbose_name='机构封面'),
        ),
    ]
