# Generated by Django 3.2.15 on 2022-09-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_courseorganization_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorganization',
            name='city',
        ),
    ]
