# Generated by Django 3.2.15 on 2022-09-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_courseorganization_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorganization',
            old_name='cateogry',
            new_name='category',
        ),
    ]
