# Generated by Django 3.2.15 on 2022-09-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_rename_cateogry_courseorganization_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorganization',
            name='courses_num',
            field=models.IntegerField(default=0, verbose_name='课程数量'),
        ),
        migrations.AddField(
            model_name='courseorganization',
            name='students_num',
            field=models.IntegerField(default=0, verbose_name='学习人数'),
        ),
    ]
