# Generated by Django 3.2.15 on 2022-10-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_teacher_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_approval',
            field=models.BooleanField(default=False, verbose_name='是否认证'),
        ),
    ]
