# Generated by Django 3.2.15 on 2022-10-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_teacher_is_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorganization',
            name='tag',
            field=models.CharField(default='', max_length=10, verbose_name='机构标签'),
        ),
    ]
