# Generated by Django 3.2.15 on 2022-09-07 11:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCourseComments',
            new_name='UserCoursesComments',
        ),
    ]
