# Generated by Django 3.2.15 on 2022-09-07 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_rename_usercoursecomments_usercoursescomments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='name',
            new_name='content',
        ),
    ]
