# Generated by Django 3.2.15 on 2022-09-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_rename_name_usermessage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userask',
            name='user',
            field=models.CharField(max_length=10, verbose_name='用户信息'),
        ),
    ]
