# Generated by Django 3.2.15 on 2022-09-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_alter_userask_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavourite',
            name='favourite_type',
            field=models.IntegerField(choices=[(1, '课程'), (2, '机构'), (3, '讲师')]),
        ),
    ]
