# Generated by Django 3.2.15 on 2022-10-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_alter_userfavourite_favourite_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavourite',
            name='favourite_type',
            field=models.IntegerField(choices=[(1, '课程'), (2, '机构'), (3, '讲师')], verbose_name='收藏类型'),
        ),
    ]
