# Generated by Django 3.2.15 on 2022-10-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_alter_userfavourite_favourite_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoursescomments',
            name='comments',
            field=models.TextField(max_length=300, verbose_name='用户评论'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='content',
            field=models.TextField(max_length=500, verbose_name='消息内容'),
        ),
    ]
