# Generated by Django 3.2.15 on 2022-10-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_alter_usermessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='消息标题'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='content',
            field=models.TextField(default='', max_length=500, verbose_name='消息内容'),
        ),
    ]
