# Generated by Django 3.2.15 on 2022-09-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_rename_name_usermessage_content'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseResource',
            new_name='CourseDownload',
        ),
        migrations.RenameModel(
            old_name='Course',
            new_name='Courses',
        ),
        migrations.RenameModel(
            old_name='Lesson',
            new_name='Lessons',
        ),
        migrations.RenameModel(
            old_name='Video',
            new_name='Videos',
        ),
    ]
