# Generated by Django 3.2.15 on 2022-09-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_carouselbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselbanner',
            name='image',
            field=models.FileField(upload_to='course/carousel/%Y/%m', verbose_name='图片路径'),
        ),
    ]
