# Generated by Django 3.2.15 on 2022-09-11 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_auto_20220911_1054'),
        ('courses', '0004_alter_carouselbanner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.courseorganization', verbose_name='课程机构'),
        ),
    ]
