# Generated by Django 3.2.15 on 2022-10-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courses_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='tag',
            field=models.CharField(default='', max_length=50, verbose_name='课程推荐标签'),
        ),
    ]
