# Generated by Django 3.2.15 on 2022-10-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_courses_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='url',
            field=models.URLField(default='', verbose_name='访问地址'),
        ),
    ]
