# Generated by Django 3.2.15 on 2022-10-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_lessons_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='url',
        ),
        migrations.AddField(
            model_name='videos',
            name='url',
            field=models.URLField(default='', verbose_name='访问地址'),
        ),
    ]
