# Generated by Django 3.2.15 on 2022-10-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20221011_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='times',
            field=models.IntegerField(default=0, verbose_name='视频时长'),
        ),
    ]
