# Generated by Django 3.2.15 on 2022-10-11 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_teacher_images'),
        ('courses', '0010_videos_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='teachers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.teacher', verbose_name='课程讲师'),
        ),
    ]
