# Generated by Django 3.2.15 on 2022-10-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_courses_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='knowledge',
            field=models.CharField(default='', max_length=300, verbose_name='课程知识点'),
        ),
        migrations.AddField(
            model_name='courses',
            name='notice',
            field=models.CharField(default='', max_length=300, verbose_name='课程须知'),
        ),
    ]
