# Generated by Django 3.2.15 on 2022-10-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20221011_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='knowledge',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='课程知识点'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='notice',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='课程须知'),
        ),
    ]
