# Generated by Django 3.2.15 on 2022-10-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20221011_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='is_carousel',
            field=models.BooleanField(default=False, verbose_name='是否作为广告位轮播图'),
        ),
    ]
