# Generated by Django 3.2.15 on 2022-10-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_emailverifyrecord_send_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='电话'),
        ),
    ]
